import ProductList from "@/app/ProductList";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Product Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex">
      <div>
        <ProductList />
      </div>
      <div className="flex-1">{children}</div>
    </main>
  );
}
